backend:
  name: git-gateway
  # repo: "tokyorak/my-recipe"
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Ingredients (English)", name: "ingredients_en", widget: "list", hint: "Add ingredients one by one and separated by ','" }
      - { label: "Ingredients (Polish)", name: "ingredients_pl", widget: "list", hint: "Add ingredients one by one and separated by ','" }
      - { label: "Instructions (English)", name: "instructions_en", widget: "markdown" }
      - { label: "Instructions (Polish)", name: "instructions_pl", widget: "markdown" }